# ステータスバー
#[[plugins]]
#repo = 'vim-airline/vim-airline'

#[[plugins]]
#repo = 'vim-airline/vim-airline-themes'
#hook_add = '''
#  let g:airline_theme='bubblegum'
#  let g:airline_powerline_fonts = 1
#  let g:airline#extensions#branch#enabled = 0
#  let g:airline#extensions#tabline#enabled = 1
#  let g:airline#extensions#readonly#enabled = 0
#  let g:airline_section_c = ''
#'''

# スクロールバー
#[[plugins]]
#repo = 'Yggdroot/indentLine'

# ファイルエクスプローラー
#[[plugins]]
#repo = 'Yggdroot/indentLine'

# 括弧補完
[[plugins]]
repo = "cohama/lexima.vim"

# 補完フレームワーク
[[plugins]]
repo = 'Shougo/deoplete.nvim'
hook_add = '''
  let g:deoplete#enable_at_startup = 1
'''

# go関連
###########################################################################
# goリアルタイム補間
[[plugins]]
repo = 'zchee/deoplete-go'
build = 'make'
hook_add = '''
  let g:deoplete#sources#go#gocode_binary = $GOPATH.'/bin/gocode'
  let g:deoplete#sources#go#sort_class = ['package', 'func', 'type', 'var', 'const']
'''
on_ft = ['go']

# auto indent
[[plugins]] # auto indent
repo = "Chiel92/vim-autoformat"

# go
[[plugins]]
repo = 'fatih/vim-go'
hook_add = '''
  let g:go_fmt_command = "goimports"
  let g:go_gocode_propose_source = 1
  let g:go_gocode_propose_builtins = 1
'''

[[plugins]] # go補完
repo = 'mdempsky/gocode'
rtp = 'nvim/'

# 定義ジャンプ
[[plugins]] 
repo = 'rogpeppe/godef'

# c++関連
############################################################################
# c++リアルタイム補間
[[plugins]]
repo = 'zchee/deoplete-clang'
hook_add = '''
  let g:deoplete#sources#clang#libclang_path = '/usr/lib/llvm-6.0/lib/libclang-6.0.so'
  let g:deoplete#sources#clang#clang_header = '/usr/include/clang'
'''

#on_ft = ['c', 'cpp', 'cmake']
#depends = ['deoplete.nvim']
#[[plugins]]
#repo = 'tweekmonster/deoplete-clang2'
#on_ft = ['c', 'cpp', 'cmake']
#depends = ['deoplete.nvim']
#[[plugins]]
#repo = 'justmao945/vim-clang'
#on_ft = ['c', 'cpp']
#[[plugins]]
#repo = 'Rip-Rip/clang_complete'
#on_ft = ['c', 'cpp']
#hook_source = '''
#  let g:clang_library_path='/usr/lib/llvm-6.0/lib'
#'''
